"""Type stubs for the `cv2` (OpenCV) module.

This project uses cv2 at runtime for computer vision tasks.
These stubs are only for IDE/static type resolution.
"""

from typing import Any, Tuple, Optional, Union, List
import numpy as np

# Constants
FONT_ITALIC: int
FONT_HERSHEY_SIMPLEX: int
FONT_HERSHEY_PLAIN: int
FONT_HERSHEY_DUPLEX: int
FONT_HERSHEY_COMPLEX: int
FONT_HERSHEY_TRIPLEX: int
FONT_HERSHEY_COMPLEX_SMALL: int
FONT_HERSHEY_SCRIPT_SIMPLEX: int
FONT_HERSHEY_SCRIPT_COMPLEX: int

COLOR_BGR2RGB: int
COLOR_BGR2GRAY: int
COLOR_RGB2BGR: int

CAP_PROP_FRAME_WIDTH: int
CAP_PROP_FRAME_HEIGHT: int
CAP_PROP_FPS: int

# Main functions
def imread(filename: str, flags: int = ...) -> Optional[np.ndarray]: ...
def imwrite(filename: str, img: np.ndarray) -> bool: ...
def cvtColor(src: np.ndarray, code: int) -> np.ndarray: ...
def rectangle(img: np.ndarray, pt1: Tuple[int, int], pt2: Tuple[int, int], color: Tuple[int, int, int], thickness: int = ...) -> np.ndarray: ...
def putText(img: np.ndarray, text: str, org: Tuple[int, int], fontFace: int, fontScale: float, color: Tuple[int, int, int], thickness: int = ...) -> np.ndarray: ...
def resize(src: np.ndarray, dsize: Tuple[int, int], interpolation: int = ...) -> np.ndarray: ...
def circle(img: np.ndarray, center: Tuple[int, int], radius: int, color: Tuple[int, int, int], thickness: int = ...) -> np.ndarray: ...
def line(img: np.ndarray, pt1: Tuple[int, int], pt2: Tuple[int, int], color: Tuple[int, int, int], thickness: int = ...) -> np.ndarray: ...

# VideoCapture class
class VideoCapture:
    def __init__(self, filename: Union[int, str]) -> None: ...
    def isOpened(self) -> bool: ...
    def read(self) -> Tuple[bool, Optional[np.ndarray]]: ...
    def release(self) -> None: ...
    def set(self, propId: int, value: float) -> bool: ...
    def get(self, propId: int) -> float: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, *args: Any) -> None: ...
